In [1]:
pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\nandy\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in c:\users\nandy\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
df_facilities = pd.read_excel('./Airport_Data.xlsx', sheet_name='Facilities')

In [4]:
df_facilities

,SiteNumber,Type,LocationID,EffectiveDate,Region,DistrictOffice,State,StateName,County,CountyState,...,AirportPositionSource,AirportPositionSourceDate,AirportElevationSource,AirportElevationSourceDate,ContractFuelAvailable,TransientStorage,OtherServices,WindIndicator,IcaoIdentifier,BeaconSchedule2
0,50009.*A,AIRPORT,'ADK,3/30/2017,AAL,NONE,AK,ALASKA,ALEUTIANS WEST,AK,...,3RD PARTY SURVEY,00:00:00,3RD PARTY SURVEY,00:00:00,NaN,HGR,CARGO,Y,PADK,SS-SR
1,50016.1*A,AIRPORT,'AKK,3/30/2017,AAL,NONE,AK,ALASKA,KODIAK ISLAND,AK,...,NACO,00:00:00,NACO,00:00:00,NaN,NaN,NaN,Y,PAKH,NaN
2,50017.*A,AIRPORT,'Z13,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,STATE,00:00:00,STATE,00:00:00,NaN,NaN,CARGO,Y-L,NaN,SEE RMK
3,50017.1*C,SEAPLANE BASE,'KKI,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN
4,50020.*A,AIRPORT,'AKI,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,STATE,00:00:00,STATE,00:00:00,NaN,NaN,CARGO,Y-L,PFAK,SS-SR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746,50920.12*C,SEAPLANE BASE,'2Y3,3/30/2017,AAL,NONE,AK,ALASKA,SKAGWAY-YAKUTAT,AK,...,FAA-EST,00:00:00,NaN,NaN,NaN,TIE,CARGO,NaN,NaN,NaN
747,50920.*A,AIRPORT,'YAK,3/30/2017,AAL,NONE,AK,ALASKA,SKAGWAY-YAKUTAT,AK,...,3RD PARTY SURVEY,00:00:00,3RD PARTY SURVEY,00:00:00,NaN,HGR,CARGO,Y-L,PAYA,SS-SR
748,50925.1*A,AIRPORT,'A77,3/30/2017,AAL,NONE,AK,ALASKA,KUSKOKWIM,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,NaN,NaN,NaN
749,50928.*C,SEAPLANE BASE,'78K,3/30/2017,AAL,NONE,AK,ALASKA,KETCHIKAN GATEWAY,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,N,NaN,NaN
750,50990.*A,AIRPORT,'L20,3/30/2017,AAL,NONE,AK,ALASKA,UPPER YUKON,AK,...,FAA-EST,00:00:00,NaN,NaN,NaN,NaN,CARGO,Y,NaN,NaN

In [6]:
df_facilities.head()

,SiteNumber,Type,LocationID,EffectiveDate,Region,DistrictOffice,State,StateName,County,CountyState,...,AirportPositionSource,AirportPositionSourceDate,AirportElevationSource,AirportElevationSourceDate,ContractFuelAvailable,TransientStorage,OtherServices,WindIndicator,IcaoIdentifier,BeaconSchedule2
0,50009.*A,AIRPORT,'ADK,3/30/2017,AAL,NONE,AK,ALASKA,ALEUTIANS WEST,AK,...,3RD PARTY SURVEY,00:00:00,3RD PARTY SURVEY,00:00:00,NaN,HGR,CARGO,Y,PADK,SS-SR
1,50016.1*A,AIRPORT,'AKK,3/30/2017,AAL,NONE,AK,ALASKA,KODIAK ISLAND,AK,...,NACO,00:00:00,NACO,00:00:00,NaN,NaN,NaN,Y,PAKH,NaN
2,50017.*A,AIRPORT,'Z13,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,STATE,00:00:00,STATE,00:00:00,NaN,NaN,CARGO,Y-L,NaN,SEE RMK
3,50017.1*C,SEAPLANE BASE,'KKI,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN
4,50020.*A,AIRPORT,'AKI,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,STATE,00:00:00,STATE,00:00:00,NaN,NaN,CARGO,Y-L,PFAK,SS-SR

In [7]:
df_facilities.tail()

,SiteNumber,Type,LocationID,EffectiveDate,Region,DistrictOffice,State,StateName,County,CountyState,...,AirportPositionSource,AirportPositionSourceDate,AirportElevationSource,AirportElevationSourceDate,ContractFuelAvailable,TransientStorage,OtherServices,WindIndicator,IcaoIdentifier,BeaconSchedule2
746,50920.12*C,SEAPLANE BASE,'2Y3,3/30/2017,AAL,NONE,AK,ALASKA,SKAGWAY-YAKUTAT,AK,...,FAA-EST,00:00:00,NaN,NaN,NaN,TIE,CARGO,NaN,NaN,NaN
747,50920.*A,AIRPORT,'YAK,3/30/2017,AAL,NONE,AK,ALASKA,SKAGWAY-YAKUTAT,AK,...,3RD PARTY SURVEY,00:00:00,3RD PARTY SURVEY,00:00:00,NaN,HGR,CARGO,Y-L,PAYA,SS-SR
748,50925.1*A,AIRPORT,'A77,3/30/2017,AAL,NONE,AK,ALASKA,KUSKOKWIM,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,NaN,NaN,NaN
749,50928.*C,SEAPLANE BASE,'78K,3/30/2017,AAL,NONE,AK,ALASKA,KETCHIKAN GATEWAY,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,N,NaN,NaN
750,50990.*A,AIRPORT,'L20,3/30/2017,AAL,NONE,AK,ALASKA,UPPER YUKON,AK,...,FAA-EST,00:00:00,NaN,NaN,NaN,NaN,CARGO,Y,NaN,NaN

In [8]:
df_facilities.head(10)

,SiteNumber,Type,LocationID,EffectiveDate,Region,DistrictOffice,State,StateName,County,CountyState,...,AirportPositionSource,AirportPositionSourceDate,AirportElevationSource,AirportElevationSourceDate,ContractFuelAvailable,TransientStorage,OtherServices,WindIndicator,IcaoIdentifier,BeaconSchedule2
0,50009.*A,AIRPORT,'ADK,3/30/2017,AAL,NONE,AK,ALASKA,ALEUTIANS WEST,AK,...,3RD PARTY SURVEY,00:00:00,3RD PARTY SURVEY,00:00:00,NaN,HGR,CARGO,Y,PADK,SS-SR
1,50016.1*A,AIRPORT,'AKK,3/30/2017,AAL,NONE,AK,ALASKA,KODIAK ISLAND,AK,...,NACO,00:00:00,NACO,00:00:00,NaN,NaN,NaN,Y,PAKH,NaN
2,50017.*A,AIRPORT,'Z13,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,STATE,00:00:00,STATE,00:00:00,NaN,NaN,CARGO,Y-L,NaN,SEE RMK
3,50017.1*C,SEAPLANE BASE,'KKI,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN
4,50020.*A,AIRPORT,'AKI,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,STATE,00:00:00,STATE,00:00:00,NaN,NaN,CARGO,Y-L,PFAK,SS-SR
5,50022.*C,SEAPLANE BASE,'KQA,3/30/2017,AAL,NONE,AK,ALASKA,ALEUTIANS EAST,AK,...,STATE,00:00:00,STATE,00:00:00,NaN,NaN,NaN,Y,NaN,NaN
6,50022.1*A,AIRPORT,'7AK,3/30/2017,AAL,NONE,AK,ALASKA,ALEUTIANS EAST,AK,...,STATE,00:00:00,3RD PARTY SURVEY,00:00:00,NaN,NaN,NaN,Y-L,PAUT,SS-SR
7,50024.1*A,AIRPORT,'AUK,3/30/2017,AAL,NONE,AK,ALASKA,WADE HAMPTON,AK,...,3RD PARTY SURVEY,00:00:00,3RD PARTY SURVEY,00:00:00,NaN,TIE,CARGO,Y-L,PAUK,SEE RMK
8,50027.52*C,SEAPLANE BASE,'Z33,3/30/2017,AAL,NONE,AK,ALASKA,BRISTOL BAY,AK,...,NaN,NaN,NaN,NaN,NaN,TIE,NaN,NaN,NaN,NaN
9,50027.53*A,AIRPORT,'5A8,3/30/2017,AAL,NONE,AK,ALASKA,BRISTOL BAY,AK,...,STATE,00:00:00,STATE,00:00:00,NaN,TIE,NaN,Y,NaN,NaN

In [9]:
df_facilities.tail(100)

,SiteNumber,Type,LocationID,EffectiveDate,Region,DistrictOffice,State,StateName,County,CountyState,...,AirportPositionSource,AirportPositionSourceDate,AirportElevationSource,AirportElevationSourceDate,ContractFuelAvailable,TransientStorage,OtherServices,WindIndicator,IcaoIdentifier,BeaconSchedule2
651,50870.73*A,AIRPORT,'AK85,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,OWNER,00:00:00,OWNER,00:00:00,NaN,NaN,NaN,Y,NaN,NaN
652,50870.6*C,SEAPLANE BASE,'D75,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,OWNER,00:00:00,OWNER,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
653,50870.25*A,AIRPORT,'71AK,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,REGION,00:00:00,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
654,50870.22*A,AIRPORT,'3AK8,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,ADO,00:00:00,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
655,50870.74*H,HELIPORT,'60AK,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,OWNER,00:00:00,OWNER,00:00:00,NaN,NaN,NaN,Y,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746,50920.12*C,SEAPLANE BASE,'2Y3,3/30/2017,AAL,NONE,AK,ALASKA,SKAGWAY-YAKUTAT,AK,...,FAA-EST,00:00:00,NaN,NaN,NaN,TIE,CARGO,NaN,NaN,NaN
747,50920.*A,AIRPORT,'YAK,3/30/2017,AAL,NONE,AK,ALASKA,SKAGWAY-YAKUTAT,AK,...,3RD PARTY SURVEY,00:00:00,3RD PARTY SURVEY,00:00:00,NaN,HGR,CARGO,Y-L,PAYA,SS-SR
748,50925.1*A,AIRPORT,'A77,3/30/2017,AAL,NONE,AK,ALASKA,KUSKOKWIM,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,NaN,NaN,NaN
749,50928.*C,SEAPLANE BASE,'78K,3/30/2017,AAL,NONE,AK,ALASKA,KETCHIKAN GATEWAY,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,N,NaN,NaN
750,50990.*A,AIRPORT,'L20,3/30/2017,AAL,NONE,AK,ALASKA,UPPER YUKON,AK,...,FAA-EST,00:00:00,NaN,NaN,NaN,NaN,CARGO,Y,NaN,NaN

In [11]:
df_facilities.shape #para saber cuantas filas y columnas contiene el DF

(751, 103)

In [14]:
df_facilities['Type'].head(10)

0          AIRPORT
1          AIRPORT
2          AIRPORT
3    SEAPLANE BASE
4          AIRPORT
5    SEAPLANE BASE
6          AIRPORT
7          AIRPORT
8    SEAPLANE BASE
9          AIRPORT
Name: Type, dtype: object

In [ ]:
df_facilities['Type'].head(10)

In [22]:
#para despliegar todas las filas del df
pd.set_option('display.max_rows',50)
df_facilities

,SiteNumber,Type,LocationID,EffectiveDate,Region,DistrictOffice,State,StateName,County,CountyState,...,AirportPositionSource,AirportPositionSourceDate,AirportElevationSource,AirportElevationSourceDate,ContractFuelAvailable,TransientStorage,OtherServices,WindIndicator,IcaoIdentifier,BeaconSchedule2
0,50009.*A,AIRPORT,'ADK,3/30/2017,AAL,NONE,AK,ALASKA,ALEUTIANS WEST,AK,...,3RD PARTY SURVEY,00:00:00,3RD PARTY SURVEY,00:00:00,NaN,HGR,CARGO,Y,PADK,SS-SR
1,50016.1*A,AIRPORT,'AKK,3/30/2017,AAL,NONE,AK,ALASKA,KODIAK ISLAND,AK,...,NACO,00:00:00,NACO,00:00:00,NaN,NaN,NaN,Y,PAKH,NaN
2,50017.*A,AIRPORT,'Z13,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,STATE,00:00:00,STATE,00:00:00,NaN,NaN,CARGO,Y-L,NaN,SEE RMK
3,50017.1*C,SEAPLANE BASE,'KKI,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN
4,50020.*A,AIRPORT,'AKI,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,STATE,00:00:00,STATE,00:00:00,NaN,NaN,CARGO,Y-L,PFAK,SS-SR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746,50920.12*C,SEAPLANE BASE,'2Y3,3/30/2017,AAL,NONE,AK,ALASKA,SKAGWAY-YAKUTAT,AK,...,FAA-EST,00:00:00,NaN,NaN,NaN,TIE,CARGO,NaN,NaN,NaN
747,50920.*A,AIRPORT,'YAK,3/30/2017,AAL,NONE,AK,ALASKA,SKAGWAY-YAKUTAT,AK,...,3RD PARTY SURVEY,00:00:00,3RD PARTY SURVEY,00:00:00,NaN,HGR,CARGO,Y-L,PAYA,SS-SR
748,50925.1*A,AIRPORT,'A77,3/30/2017,AAL,NONE,AK,ALASKA,KUSKOKWIM,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,NaN,NaN,NaN
749,50928.*C,SEAPLANE BASE,'78K,3/30/2017,AAL,NONE,AK,ALASKA,KETCHIKAN GATEWAY,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,N,NaN,NaN
750,50990.*A,AIRPORT,'L20,3/30/2017,AAL,NONE,AK,ALASKA,UPPER YUKON,AK,...,FAA-EST,00:00:00,NaN,NaN,NaN,NaN,CARGO,Y,NaN,NaN

In [17]:
df_facilities["Type"].unique()

array(['AIRPORT', 'SEAPLANE BASE', 'HELIPORT'], dtype=object)

In [18]:
df_facilities.dtypes

SiteNumber                     object
Type                           object
LocationID                     object
EffectiveDate                  object
Region                         object
DistrictOffice                 object
State                          object
StateName                      object
County                         object
CountyState                    object
City                           object
FacilityName                   object
Ownership                      object
Use                            object
Owner                          object
OwnerAddress                   object
OwnerCSZ                       object
OwnerPhone                     object
Manager                        object
ManagerAddress                 object
ManagerCSZ                     object
ManagerPhone                   object
ARPLatitude                    object
ARPLatitudeS                   object
ARPLongitude                   object
ARPLongitudeS                  object
ARPMethod                      object
ARPElevation                    int64
ARPElevationMethod             object
MagneticVariation              object
MagneticVariationYear         float64
TrafficPatternAltitude        float64
ChartName                      object
DistanceFromCBD               float64
DirectionFromCBD               object
LandAreaCoveredByAirport      float64
BoundaryARTCCID                object
BoundaryARTCCComputerID        object
BoundaryARTCCName              object
ResponsibleARTCCID             object
ResponsibleARTCCComputerID     object
ResponsibleARTCCName           object
TieInFSS                       object
TieInFSSID                     object
TieInFSSName                   object
AirportToFSSPhoneNumber        object
TieInFSSTollFreeNumber         object
AlternateFSSID                 object
AlternateFSSName               object
AlternateFSSTollFreeNumber     object
NOTAMFacilityID                object
NOTAMService                   object
ActivationDate                 object
AirportStatusCode              object
CertificationTypeDate          object
FederalAgreements              object
AirspaceDetermination          object
CustomsAirportOfEntry          object
CustomsLandingRights           object
MilitaryJointUse               object
MilitaryLandingRights          object
InspectionMethod               object
InspectionGroup                object
LastInspectionDate            float64
LastOwnerInformationDate      float64
FuelTypes                      object
AirframeRepair                 object
PowerPlantRepair               object
BottledOxygenType              object
BulkOxygenType                 object
LightingSchedule               object
BeaconSchedule                 object
ATCT                           object
UNICOMFrequencies             float64
CTAFFrequency                 float64
SegmentedCircle                object
BeaconColor                    object
NonCommercialLandingFee        object
MedicalUse                     object
SingleEngineGA                float64
MultiEngineGA                 float64
JetEngineGA                   float64
HelicoptersGA                 float64
GlidersOperational            float64
MilitaryOperational           float64
Ultralights                   float64
OperationsCommercial          float64
OperationsCommuter            float64
OperationsAirTaxi             float64
OperationsGALocal             float64
OperationsGAItin              float64
OperationsMilitary            float64
OperationsDate                 object
AirportPositionSource          object
AirportPositionSourceDate      object
AirportElevationSource         object
AirportElevationSourceDate     object
ContractFuelAvailable         float64
TransientStorage               object
OtherServices                  object
WindIndicator                  object
IcaoIdentifier                 object
BeaconSchedule2                object
dtype: object

In [21]:
df_facilities['Type']== 'SEAPLANE BASE'

0      False
1      False
2      False
3       True
4      False
5       True
6      False
7      False
8       True
9      False
10     False
11     False
12     False
13     False
14     False
15      True
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24      True
25     False
26     False
27     False
28     False
29      True
30     False
31     False
32     False
33     False
34     False
35     False
36      True
37     False
38     False
39      True
40     False
41      True
42     False
43     False
44     False
45     False
46     False
47      True
48     False
49     False
50      True
51     False
52     False
53     False
54     False
55     False
56      True
57     False
58      True
59     False
60      True
61     False
62      True
63      True
64     False
65      True
66     False
67     False
68     False
69     False
70     False
71     False
72      True
73      True
74      True
75      True
76     False
77      True
78     False
79      True
80     False
81     False
82     False
83     False
84     False
85      True
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101     True
102    False
103    False
104    False
105    False
106    False
107    False
108    False
109     True
110    False
111    False
112    False
113    False
114    False
115    False
116    False
117     True
118    False
119    False
120    False
121    False
122    False
123    False
124    False
125    False
126    False
127     True
128    False
129    False
130    False
131     True
132     True
133    False
134    False
135    False
136    False
137    False
138    False
139    False
140    False
141    False
142    False
143     True
144    False
145     True
146    False
147    False
148    False
149    False
150    False
151    False
152    False
153    False
154    False
155    False
156    False
157    False
158    False
159    False
160    False
161    False
162    False
163    False
164    False
165    False
166    False
167    False
168    False
169    False
170    False
171    False
172     True
173    False
174    False
175    False
176     True
177    False
178    False
179    False
180    False
181    False
182    False
183     True
184    False
185    False
186     True
187    False
188     True
189    False
190    False
191    False
192     True
193    False
194     True
195    False
196    False
197    False
198    False
199    False
200    False
201    False
202    False
203    False
204    False
205    False
206    False
207    False
208    False
209     True
210    False
211    False
212     True
213    False
214    False
215    False
216    False
217    False
218    False
219    False
220     True
221    False
222    False
223    False
224    False
225    False
226    False
227    False
228    False
229     True
230    False
231    False
232    False
233    False
234    False
235    False
236    False
237    False
238    False
239    False
240    False
241     True
242    False
243    False
244     True
245    False
246    False
247    False
248    False
249    False
250     True
251    False
252    False
253    False
254    False
255    False
256    False
257    False
258    False
259     True
260    False
261     True
262    False
263    False
264    False
265    False
266    False
267    False
268     True
269    False
270    False
271    False
272    False
273    False
274     True
275     True
276    False
277    False
278    False
279    False
280    False
281     True
282    False
283    False
284    False
285    False
286     True
287    False
288    False
289    False
290     True
291    False
292    False
293    False
294    False
295    False
296    False
297    False
298    False
299    False
300     True
301     True
302    False
303     True
304    False
305     True
306    False
307    False
308    False
309    False
310    False
311    False
312     True
313     True
314    False
315    False
316    False
317    False
318     True
319    False
320    False
321     True
322     True
323    False
324    False
325    False
326    False
327    False
328     True
329    False
330     True
331    False
332    False
333    False
334     True
335    False
336     True
337    False
338    False
339    False
340    False
341    False
342    False
343    False
344    False
345    False
346    False
347    False
348    False
349    False
350    False
351    False
352     True
353    False
354    False
355    False
356     True
357    False
358    False
359    False
360    False
361    False
362    False
363     True
364    False
365    False
366    False
367    False
368    False
369    False
370    False
371    False
372    False
373    False
374    False
375    False
376     True
377    False
378    False
379    False
380    False
381    False
382     True
383     True
384    False
385    False
386    False
387    False
388    False
389     True
390     True
391    False
392    False
393    False
394    False
395    False
396     True
397    False
398    False
399    False
400    False
401    False
402    False
403    False
404    False
405    False
406     True
407    False
408    False
409    False
410    False
411    False
412    False
413    False
414    False
415    False
416    False
417    False
418    False
419    False
420    False
421    False
422    False
423    False
424    False
425    False
426     True
427    False
428    False
429    False
430    False
431    False
432    False
433    False
434    False
435    False
436    False
437     True
438    False
439    False
440    False
441    False
442    False
443    False
444    False
445    False
446    False
447    False
448     True
449    False
450    False
451     True
452    False
453    False
454    False
455    False
456    False
457    False
458    False
459    False
460    False
461    False
462     True
463    False
464     True
465    False
466    False
467    False
468    False
469     True
470     True
471    False
472     True
473    False
474    False
475    False
476    False
477    False
478    False
479     True
480    False
481    False
482    False
483    False
484    False
485    False
486    False
487    False
488    False
489    False
490     True
491     True
492    False
493    False
494     True
495    False
496    False
497    False
498    False
499     True
500     True
501     True
502    False
503    False
504    False
505    False
506    False
507    False
508    False
509    False
510    False
511    False
512    False
513    False
514    False
515    False
516     True
517    False
518     True
519    False
520    False
521    False
522    False
523    False
524    False
525     True
526    False
527    False
528    False
529    False
530    False
531    False
532    False
533    False
534    False
535     True
536     True
537    False
538    False
539    False
540    False
541    False
542    False
543    False
544    False
545    False
546    False
547    False
548    False
549    False
550    False
551     True
552    False
553    False
554    False
555    False
556    False
557    False
558     True
559    False
560    False
561    False
562    False
563     True
564    False
565    False
566    False
567    False
568    False
569    False
570    False
571    False
572    False
573    False
574    False
575    False
576    False
577    False
578    False
579    False
580     True
581     True
582    False
583    False
584    False
585    False
586     True
587    False
588    False
589    False
590    False
591    False
592    False
593    False
594    False
595    False
596    False
597    False
598    False
599    False
600    False
601    False
602    False
603     True
604    False
605    False
606     True
607    False
608     True
609     True
610    False
611    False
612    False
613    False
614    False
615     True
616    False
617     True
618    False
619    False
620    False
621    False
622    False
623    False
624    False
625     True
626    False
627    False
628     True
629    False
630    False
631    False
632    False
633    False
634    False
635    False
636    False
637    False
638    False
639    False
640    False
641     True
642    False
643    False
644    False
645    False
646    False
647    False
648    False
649    False
650    False
651    False
652     True
653    False
654    False
655    False
656    False
657     True
658    False
659    False
660    False
661    False
662    False
663    False
664    False
665    False
666    False
667    False
668    False
669     True
670    False
671     True
672    False
673     True
674    False
675    False
676     True
677     True
678    False
679    False
680    False
681     True
682    False
683    False
684     True
685    False
686     True
687     True
688    False
689    False
690    False
691    False
692    False
693     True
694    False
695    False
696    False
697    False
698    False
699    False
700    False
701    False
702    False
703    False
704     True
705    False
706     True
707     True
708    False
709     True
710    False
711    False
712    False
713     True
714     True
715    False
716    False
717    False
718    False
719    False
720    False
721     True
722    False
723     True
724    False
725     True
726    False
727    False
728    False
729    False
730    False
731    False
732    False
733    False
734     True
735    False
736    False
737     True
738    False
739    False
740    False
741    False
742    False
743    False
744    False
745    False
746     True
747    False
748    False
749     True
750    False
Name: Type, dtype: bool

In [23]:
df_facilities[df_facilities["Type"] == "SEAPLANE BASE"]

,SiteNumber,Type,LocationID,EffectiveDate,Region,DistrictOffice,State,StateName,County,CountyState,...,AirportPositionSource,AirportPositionSourceDate,AirportElevationSource,AirportElevationSourceDate,ContractFuelAvailable,TransientStorage,OtherServices,WindIndicator,IcaoIdentifier,BeaconSchedule2
3,50017.1*C,SEAPLANE BASE,'KKI,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN
5,50022.*C,SEAPLANE BASE,'KQA,3/30/2017,AAL,NONE,AK,ALASKA,ALEUTIANS EAST,AK,...,STATE,00:00:00,STATE,00:00:00,NaN,NaN,NaN,Y,NaN,NaN
8,50027.52*C,SEAPLANE BASE,'Z33,3/30/2017,AAL,NONE,AK,ALASKA,BRISTOL BAY,AK,...,NaN,NaN,NaN,NaN,NaN,TIE,NaN,NaN,NaN,NaN
15,50031.5*C,SEAPLANE BASE,'AK81,3/30/2017,AAL,NONE,AK,ALASKA,KODIAK ISLAND,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN
24,50035.2*C,SEAPLANE BASE,'3C3,3/30/2017,AAL,NONE,AK,ALASKA,ANCHORAGE,AK,...,OWNER,00:00:00,OWNER,00:00:00,NaN,NaN,NaN,Y,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,50877.32*C,SEAPLANE BASE,'MFN,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,OWNER,00:00:00,OWNER,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
734,50877.01*C,SEAPLANE BASE,'2X2,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,FAA-EST,00:00:00,STATE,00:00:00,NaN,TIE,CHTR,Y,NaN,NaN
737,50905.*C,SEAPLANE BASE,'68A,3/30/2017,AAL,NONE,AK,ALASKA,WRANGELL-PETERSBURG,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,Y,NaN,NaN
746,50920.12*C,SEAPLANE BASE,'2Y3,3/30/2017,AAL,NONE,AK,ALASKA,SKAGWAY-YAKUTAT,AK,...,FAA-EST,00:00:00,NaN,NaN,NaN,TIE,CARGO,NaN,NaN,NaN
749,50928.*C,SEAPLANE BASE,'78K,3/30/2017,AAL,NONE,AK,ALASKA,KETCHIKAN GATEWAY,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,N,NaN,NaN

In [24]:
df_facilities.sort_values(by = "ARPElevation", ascending = False)

,SiteNumber,Type,LocationID,EffectiveDate,Region,DistrictOffice,State,StateName,County,CountyState,...,AirportPositionSource,AirportPositionSourceDate,AirportElevationSource,AirportElevationSourceDate,ContractFuelAvailable,TransientStorage,OtherServices,WindIndicator,IcaoIdentifier,BeaconSchedule2
584,50739.1*A,AIRPORT,'AA09,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
630,50738.20*A,AIRPORT,'93AK,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,OWNER,00:00:00,OWNER,00:00:00,NaN,NaN,CARGO,Y,NaN,NaN
265,50324.6*A,AIRPORT,'4Z5,3/30/2017,AAL,NONE,AK,ALASKA,SOUTHEAST FAIRBANKS,AK,...,FAA OE/AAA,00:00:00,FAA OE/AAA,00:00:00,NaN,NaN,NaN,Y,NaN,NaN
582,50738.01*A,AIRPORT,'2AK7,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,50439.18*A,AIRPORT,'AK80,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,OWNER,00:00:00,OWNER,00:00:00,NaN,NaN,NaN,Y,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,50196.3*C,SEAPLANE BASE,'ELV,3/30/2017,AAL,NONE,AK,ALASKA,SKAGWAY-YAKUTAT,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAEL,NaN
516,50680.*C,SEAPLANE BASE,'A23,3/30/2017,AAL,NONE,AK,ALASKA,WRANGELL-PETERSBURG,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,NaN,NaN,NaN
363,50455.6*C,SEAPLANE BASE,'13Z,3/30/2017,AAL,NONE,AK,ALASKA,KETCHIKAN GATEWAY,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN
382,50489.*C,SEAPLANE BASE,'MTM,3/30/2017,AAL,NONE,AK,ALASKA,KETCHIKAN GATEWAY,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,Y,PAMM,NaN
628,50773.5*C,SEAPLANE BASE,'AK62,3/30/2017,AAL,NONE,AK,ALASKA,KETCHIKAN GATEWAY,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,N,NaN,NaN

In [25]:
df_facilities["ARPElevation"].mean()

425.93209054593876

In [26]:
df_facilities["ARPElevation"].max()

3984

In [27]:
df_facilities["ARPElevation"].min()

0

In [30]:
df_seaplane = df_facilities[df_facilities["Type"] == "SEAPLANE BASE"]

In [31]:
df_seaplane.to_excel("./seaplane.xlsx")